name: Run all tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    env:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Use Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Log APPLITOOLS_API_KEY
        run: echo "APPLITOOLS_API_KEY=$APPLITOOLS_API_KEY"

      - name: Install dependencies
        run: mvn install

      - name: Test code
        run: mvn exec:exec -Dexec.mainClass=com.applitools.example.BankTest
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          HEADLESS: true
